server:
  port: 80
  servlet:
    context-path: /nanyahuayi
    
spring:  
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
  datasource: 
    url: jdbc:mysql://129.204.173.36:3306/nanya?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: NANyahuayi123,
    driver-class-name: com.mysql.jdbc.Driver
  jpa: 
    properties: 
      hibernate: 
        hbm2ddl: 
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

logging: 
  config: classpath:logback-spring.xml

#定义图片基础目录、基础访问路径
image: 
  product: 
    base-directory: D:/nginx/html/dist
    base-url: http://localhost:8000