server:
  port: 80
  servlet:
    context-path: /nanyahuayi
    
spring: 
  datasource: 
    url: jdbc:mysql://129.204.173.36:3306/nanya?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: NANyahuayi123,
    driver-class-name: com.mysql.jdbc.Driver
  jpa: 
    properties: 
      hibernate: 
        hbm2ddl: 
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

logging: 
  config: classpath:logback-spring.xml
  
student.name: nestor